### ISSUE TITLE
minor fix suggested

### ISSUE THREAD

**Issue by jpiaskowski** [yonicd/texsnippets#1]
I used devtools to install this. but, should installation instructions read: 

remotes::install_github('yonicd/texsnippets')

(plural on "remotes'). It works nice in .R files, thanks. It required a full restart of RStudio, not just a restarting a session, for the new functions to take effect.

**Comment by yonicd** [comment]
thank you. 

I updated the readme to fix the typo. 

The message from the add_snippets returns the message

"Restart RStudio to have access to the snippets.", which seems to be ok.
